### Test home route
GET http://localhost:8080/

### Get all contacts
GET http://localhost:8080/contacts

### Get one contact
GET http://localhost:8080/contacts/6aad6f89f2d3ed1e4e39f3a7

### Create contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "Victoria",
    "lastName": "Aguilar",
    "email": "victoria@example.com",
    "favoriteColor": "Purple",
    "birthday": "2021-02-05"
}

### Update Contact
PUT http://localhost:8080/contacts/6aad6f89f2d3ed1e4e39f3a7
Content-Type: application/json

{
    "firstName": "Nefi",
    "lastName": "Aguilar",
    "email": "updated3@example.com",
    "favoriteColor": "green",
    "birthday": "1995-01-01"
}

### Delete one contact
DELETE http://localhost:8080/contacts/6aba99b989e5ae0bf46f649d